FROM python:3.9
WORKDIR /app
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev
COPY ./app/requirements.txt ./
RUN pip install -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["python", "app.py"]